In [7]:
def monitoring(TimeStamp1, TimeStamp2, RTE):
    import sys,os, pdb, sqlite3
    #Check and see if the current working path exists in python system.
    #otherwise add it.
    curr_path = 'd:\\Nextcloud\\Thermal Battery Research\\modelling\\python'
    if curr_path not in sys.path:
        sys.path.append('d:\\Nextcloud\\Thermal Battery Research\\modelling\\python')
        print('Path added!')

    from projdirs import datadir
    from package.optimisation import optimise, load_simparams
    import matplotlib.pyplot as plt 
    import numpy as np
    import pandas as pd
    import os, pdb, sqlite3
    import package.get_NEM_data as gd
    from IPython.display import clear_output
    from datetime import datetime, timedelta

    connection = sqlite3.connect(datadir + 'arbitrage\\' + 'storage_value_rolling_forecast.db')
    cursor = connection.cursor()

    cursor.execute("SELECT * FROM storage_value WHERE state=" + '"'+'NSW'+'"')
    data = pd.DataFrame([row for row in cursor.fetchall()])



    data.columns = ['state','date_time', 'sh', 'rte', 'cap', 'loss', 'window',
                        'Pin', 'Pout', 'Q_start', 'Q_end', 'obj']
    data['date_time'] = pd.to_datetime(data['date_time'])
    data.set_index(data['date_time'], inplace=True)
    data = data[data['rte']==RTE]
    return(data.loc[TimeStamp1:TimeStamp2])

monitoring('2010-01-01 05:00:00','2010-01-01 06:00:00', RTE=40)

# Slice =  data.loc[pd.Timestamp('2018-01-01'): pd.Timestamp('2018-12-31')]

# fig, ax1 = plt.subplots(figsize=(16,4))
# ax2 = ax1.twinx()

# ax1.plot(Slice.index, Slice['Q_end'], color='b')
# ax2.step(Slice.index, Slice['Pin'], color='g')
# ax2.step(Slice.index, Slice['Pout'], color='r')
# ax2.set_ylim([-10,60])
# # plt.ylim([-10,60])
# plt.grid()
# plt.show()
# print(gd.load_actual_rrp_at('NSW', pd.Timestamp('2018-01-01 04:00:00')))
# print(50*14500*0.5)
# data['rrp'] = gd.load_actual_rrp_at('NSW', data['date_time'])
# data['obj'] = (data['Pout']-data['Pin'])*0.5*data['rrp']
# data['obj'].sum()
# data.reset_index
# data.drop('rrp',axis=1, inplace=True)
# data = data.reset_index(drop=True)
# plt.close("all")
# data.to_sql( "storage_value", connection, if_exists="replace", index=False)

,state,date_time,sh,rte,cap,loss,window,Pin,Pout,Q_start,Q_end,obj
date_time,,,,,,,,,,,,
2010-01-01 05:00:00,NSW,2010-01-01 05:00:00,10,40,14500,0,46,0.0,0.0,0,0.0,0.0
2010-01-01 05:30:00,NSW,2010-01-01 05:30:00,10,40,14500,0,45,0.0,0.0,0,0.0,0.0
2010-01-01 06:00:00,NSW,2010-01-01 06:00:00,10,40,14500,0,44,0.0,0.0,0,0.0,0.0

In [2]:
import sys,os
    #Check and see if the current working path exists in python system.
    #otherwise add it.
curr_path = 'c:\\Nextcloud\\Thermal Battery Research\\modelling\\python'
if curr_path not in sys.path:
    sys.path.append(curr_path)
    print('Path added!')
    
from projdirs import datadir
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import package.get_NEM_data as gd
import package.sql_manager as sm

Year = 2010
RTE=40
state = 'SA'
db = 'storage_value_PF_simple_%s.db'%(state)
table = 'storage_value'
cols = [x[0] for x in sm.list_columns(db,table)]
data = sm.get_data(cols,table, db)

print(data)

   state  date_time  sh  rte  loss    cap      SV
0     SA       2011   2   30     0  14500    0.00
1     SA       2010   2   30     0  14500    0.00
2     SA       2012   2   30     0  14500    0.00
3     SA       2013   2   30     0  14500    0.00
4     SA       2014   2   30     0  14500    0.00
5     SA       2015   2   30     0  14500    0.00
6     SA       2016   2   30     0  14500    0.00
7     SA       2017   2   30     0  14500    0.00
8     SA       2018   2   30     0  14500    0.00
9     SA       2010   3   30     0  14500    0.00
10    SA       2011   3   30     0  14500    0.00
11    SA       2012   3   30     0  14500    0.00
12    SA       2013   3   30     0  14500    0.00
13    SA       2014   3   30     0  14500    0.00
14    SA       2015   3   30     0  14500    0.00
15    SA       2016   3   30     0  14500    0.00
16    SA       2017   3   30     0  14500    0.00
17    SA       2018   3   30     0  14500    0.00
18    SA       2010   4   30     0  14500    0.00
19    SA       2011   4   30     0  14500    0.00
20    SA       2012   4   30     0  14500    0.00
21    SA       2013   4   30     0  14500    0.00
22    SA       2014   4   30     0  14500    0.00
23    SA       2015   4   30     0  14500    0.00
24    SA       2016   4   30     0  14500    0.00
25    SA       2017   4   30     0  14500    0.00
26    SA       2018   4   30     0  14500    0.00
27    SA       2010   5   30     0  14500    0.00
28    SA       2011   5   30     0  14500    0.00
29    SA       2012   5   30     0  14500    0.00
..   ...        ...  ..  ...   ...    ...     ...
38    SA       2012   6   30     0  14500    0.00
39    SA       2013   6   30     0  14500    0.00
40    SA       2014   6   30     0  14500 -969.75
41    SA       2015   6   30     0  14500    0.00
42    SA       2016   6   30     0  14500    0.00
43    SA       2017   6   30     0  14500    0.00
44    SA       2018   6   30     0  14500    0.00
45    SA       2010   7   30     0  14500    0.00
46    SA       2011   7   30     0  14500    0.00
47    SA       2012   7   30     0  14500    0.00
48    SA       2013   7   30     0  14500    0.00
49    SA       2014   7   30     0  14500 -969.75
50    SA       2015   7   30     0  14500    0.00
51    SA       2016   7   30     0  14500    0.00
52    SA       2017   7   30     0  14500    0.00
53    SA       2018   7   30     0  14500    0.00
54    SA       2010   8   30     0  14500    0.00
55    SA       2011   8   30     0  14500    0.00
56    SA       2012   8   30     0  14500    0.00
57    SA       2013   8   30     0  14500    0.00
58    SA       2014   8   30     0  14500 -969.75
59    SA       2015   8   30     0  14500    0.00
60    SA       2016   8   30     0  14500    0.00
61    SA       2017   8   30     0  14500    0.00
62    SA       2018   8   30     0  14500    0.00
63    SA       2010   9   30     0  14500    0.00
64    SA       2011   9   30     0  14500    0.00
65    SA       2012   9   30     0  14500    0.00
66    SA       2013   9   30     0  14500    0.00
67    SA       2014   9   30     0  14500 -969.75

[68 rows x 7 columns]